-- Enable Row Level Security (RLS) on all tables is a best practice
-- but for simplicity in this template, we will set up basic policies.

-- 1. PROFILES TABLE (For Admin Users)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'user', -- 'admin' or 'user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. STATIC CONTENT TABLE (For Text & Image URLs)
create table static_content (
  key text primary key, -- e.g. 'me_hero_title', 'me_about_text'
  content text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table static_content enable row level security;

create policy "Content is viewable by everyone"
  on static_content for select
  using ( true );

create policy "Only admins can insert content"
  on static_content for insert
  with check ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Only admins can update content"
  on static_content for update
  using ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- 3. PRODUCTS TABLE (Optional, for Services if you want them dynamic later)
create table products (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  price numeric,
  image_url text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table products enable row level security;

create policy "Products are viewable by everyone"
  on products for select
  using ( true );

create policy "Only admins can modify products"
  on products for all
  using ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- 4. STORAGE SETUP (Bucket for Images)
-- You must manually create a bucket named 'images' in the Storage dashboard if this fails,
-- but the policies below explain the logic.

insert into storage.buckets (id, name, public) values ('images', 'images', true);

create policy "Images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'images' );

create policy "Admins can upload images"
  on storage.objects for insert
  with check (
    bucket_id = 'images' AND
    auth.role() = 'authenticated' AND
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Admins can update images"
  on storage.objects for update
  using (
    bucket_id = 'images' AND
    auth.role() = 'authenticated' AND
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

create policy "Admins can delete images"
  on storage.objects for delete
  using (
    bucket_id = 'images' AND
    auth.role() = 'authenticated' AND
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- 5. FUNCTION TO HANDLE NEW USERS
-- Automatically creates a profile entry when a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user'); -- Default role is 'user'. You must manually change to 'admin' in Table Editor.
  return new;
end;
$$;

-- Trigger the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
