-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Create Profiles Table (if not exists)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  role text default 'client', -- 'admin' or 'client'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Handle New User Signup (Trigger)
-- This ensures every new user in auth.users gets a row in public.profiles
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'client');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger checks
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Create Messages Table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null, -- The client involved
  sender_id uuid references public.profiles(id) not null, -- Who actually sent it (client or admin)
  content text not null,
  is_admin_reply boolean default false, -- Helper to quickly know if it's from admin
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Realtime
alter publication supabase_realtime add table public.messages;

-- 5. RLS Policies (Security)
alter table public.profiles enable row level security;
alter table public.messages enable row level security;

-- Profiles: Users can see their own profile. Admins can see all.
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Messages: 
-- Client can see their own messages.
-- Admin ('admin' role) can see all messages.
create policy "Users can see own messages"
  on messages for select
  using ( auth.uid() = user_id );

create policy "Admins can see all messages"
  on messages for select
  using ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Users can insert own messages"
  on messages for insert
  with check ( auth.uid() = sender_id );

-- Allow admins to insert messages (replies)
create policy "Admins can insert replies"
  on messages for insert
  with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
