-- APPOINTMENTS SETUP

-- 1. Create Appointments Table
create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id uuid references public.profiles(id), -- Nullable for manual guests
  client_name text, -- For manual entries
  start_time timestamp with time zone not null,
  end_time timestamp with time zone, -- Optional, can assume 1h
  status text default 'confirmed', -- 'pending', 'confirmed', 'cancelled'
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RLS Policies
alter table public.appointments enable row level security;

-- Admin can see/edit ALL
create policy "Admins manage all appointments"
  on appointments for all
  using ( 
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Clients can see/create THEIR OWN
create policy "Clients view own appointments"
  on appointments for select
  using ( auth.uid() = client_id );

create policy "Clients create appointments"
  on appointments for insert
  with check ( auth.uid() = client_id );

-- 3. Enable Realtime
alter publication supabase_realtime add table public.appointments;
