-- Table des indisponibilités admin
CREATE TABLE IF NOT EXISTS public.unavailabilities (
  id bigint generated by default as identity primary key,
  start_date date not null,
  end_date date not null,
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.unavailabilities ENABLE ROW LEVEL SECURITY;

-- Seul l'admin peut créer/modifier/supprimer
CREATE POLICY "Admins manage unavailabilities"
  ON unavailabilities FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Tout le monde peut lire (pour bloquer les dates côté client)
CREATE POLICY "Anyone can view unavailabilities"
  ON unavailabilities FOR SELECT
  USING (true);
